name: ChatProtection
main: Luthfi\ChatProtection\Main
version: 0.0.2
api: 5.0.0
author: Luthfi
description: A plugin to protect your chat from spam and other unwanted behavior.
website: https://github.com/LuthMC/ChatProtection
commands:
  lockchat:
    description: Locks the chat.
    usage: /lockchat
    permission: chatprotection.lock
  unlockchat:
    description: Unlocks the chat.
    usage: /unlockchat
    permission: chatprotection.unlock
  clearchat:
    description: Clears the chat.
    usage: /clearchat
    permission: chatprotection.clearchat
permissions:
  chatprotection.lock:
    description: Allows the player to lock the chat.
    default: op
  chatprotection.unlock:
    description: Allows the player to unlock the chat.
    default: op
  chatprotection.clearchat:
    description: Allows the player to clear the chat.
    default: op
  chatprotection.notify:
    description: Allows the player to receive notifications about spamming.
    default: op
