# ChatProtection Configuration
# Github: https://github.com/LuthMC/ChatProtection

config_version: "1.0.0" # Don't change this!

anti-spam:
  enabled: true
  max_messages_per_second: 3
  kick_on_spam: true
  kick_message: "You have been kicked for spamming."

anti-command-spam:
  enabled: true
  max_commands_per_second: 2
  kick_on_spam: true
  kick_message: "You have been kicked for command spamming."

anti-caps:
  enabled: true
  min_length: 5
  caps_threshold: 70
  warning_message: "{prefix}Please do not use too many caps."

anti-advertise:
  enabled: true
  blocked_domains:
    - "example.com"
    - "anotherexample.com"
  warning_message: "{prefix}Advertising is not allowed on this server."
  kick_on_advertise: true
  kick_message: "You have been kicked for advertising."
